### ISSUE TITLE
What was the longitude problem with Adafruit_gps?

### ISSUE THREAD

**Issue by MechanicalPython** [chakflying/rpi-gps-recorder#1]
Hi, you mention in your dependancies for pi-gps-recorder that adafruit_gps parses longitudes incorrectly but I can't see how you've fixed the issue. If you're able to share how you fixed it or what the parsing problem was I'd love to be able to fix the issue in the source code.

**Comment by chakflying** [comment]
Hi! I left a comment on the [original issue](https://github.com/MechanicalPython/adafruit_gps/issues/2), but basically when longitude is 3 digits the value is not parsed correctly. I added a quick hack by checking if the string is longer.
